[flask]
SQLALCHEMY_DATABASE_URI = "postgresql://username:password@localhost/databasename8"
SECRET_KEY = "your-secret-key"
APPLICATION_ROOT = ""
DEBUG = true
HOST = "0.0.0.0"
PORT = 5000

[submissions]
UPLOAD_FOLDER = "app/static/submissions"