[flask]
SQLALCHEMY_DATABASE_URI = "postgresql://username:password@localhost/databasename8"
SECRET_KEY = "your-secret-key"
APPLICATION_ROOT = ""
DEBUG = true
HOST = "0.0.0.0"
PORT = 5000
SESSION_COOKIE_SECURE = false
SESSION_COOKIE_HTTPONLY = true
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_PROTECTION = 'strong'
SESSION_COOKIE_NAME = 'session66'

[submissions]
UPLOAD_FOLDER = "app/static/submissions"